version: "3.3"

services:
  jenkins:
   image: jenkins/jenkins:lts-jdk17
   privileged: true
   container_name: jenkins
   user: root
   ports:
     - "8080:8080"
     - "50000:50000"
   
   volumes:
     - /home/jimbo/jenkins_home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock

   expose:
     - 4444

   networks:
     - jenkins-network

  agent1:
    image: jenkins/ssh-agent:alpine-jdk17
    privileged: true 
    user: root
    container_name: agent1
    expose:
      - 22
    volumes:
      - /home/jimbo/agent1:/home/jimbo
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILYgS/SWHCYVfD7PWNMn0vgdPf2sgW1YRKN88SNt0+kC jimbo@jimbo-Virtual-Machine
    networks:
      - jenkins-network




 


